### ISSUE TITLE
internal server err: create share 

### ISSUE THREAD

**Issue by bharathganji** [KeepShareOrg/keepshare#6]
## Description

**i received error when i trying to create share**
// 20240120101201
// https://keepshare.org/8q50opk7/magnet%3A%3Fxt%3Durn%3Abtih%3Ae74dbdaeca29c1538959a63140a00d1efcab8143

{
  "error": "internal",
  "message": "internal server err: create share error: create share from links err: create from link error: get token err: unexpected body: <html><head><style>body{font-family:sans-serif}.b{display:flex;align-items:center;justify-content:center;height:80%}.s{border-bottom:1px solid#eee;margin-bottom:16px}.n{font-size:28px;font-weight:700}</style><title id=\"t1\">Block page</title></head><body><div class='b'><div><div><div class='n' id=\"c0\">Blocked</div><div id=\"c1\">Sorry, your request is a suscipious threat to the website and blocked by the defense system.</div><div id=\"c2\">Please contact the system administrator to whitelist your access if it is a false positive.</div><div id=\"c3\">Your request id is </div><div>0a0002d517057257243674276e0b4a</div><div class='s'></div><div></div></div></div></div></body></html>\n<script type=\"text/javascript\">var lang=navigator.language||navigator.browserLanguage;if(/^zh/.test(lang)){document.getElementById(\"t1\").innerText=\"阻断页面\";document.getElementById(\"c0\").innerText=\"已阻断\";document.getElementById(\"c1\").innerText=\"很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断\";document.getElementById(\"c2\").innerText=\"如果您是正常访问，请联系该业务系统管理员加白或其他方法处理 \";document.getElementById(\"c3\").innerText=\"您的请求ID是：\"}</script>"
}

**Comment by CodeCraftsfolk** [comment]
The reason for this error: During the peak request period, our request triggered PikPak's interception, and then it was automatically restored.
